### ISSUE TITLE
Would like the word 'Appendix' to appear in Appendix titles. 

### ISSUE THREAD

**Issue by andrew-edwards** [andrew-edwards/csas-latex#1]
Have tried numerous times - see .sty file. Rowan may have a fix (and Jaclyn from 2012?).

**Comment by andrew-edwards** [comment]
Andy fixed for Redbanded assessment (and other minor title things), but it's part of the .tex not the .sty. So need to produce a simpler working example.

**Comment by cgrandin** [comment]
This is fixed in my mwe branch: https://github.com/cgrandin/csas-latex/tree/mwe

**Comment by andrew-edwards** [comment]
That branch does not exist any more - presume it's been merged in and is all fine in csas-style repo. Seems to work for me.
